# this file is *not* meant to cover or endorse the use of travis, but rather to
# help confirm pull requests to this project.

matrix:
    include:
        - os: linux
          python: 2.7
          env: TOXENV=py27
        - os: linux
          python: 3.3
          env: TOXENV=py34
        - os: osx
          language: generic
          env: TOXENV=py27
        - os: osx
          language: generic
          env: TOXENV=py34

install: pip install tox

script: tox

notifications:
  email: false
