# this file is *not* meant to cover or endorse the use of travis, but rather to
# help confirm pull requests to this project.

language: python

env:
  - TOXENV=py27-win
  - TOXENV=py27-linux
  - TOXENV=py34-win
  - TOXENV=py34-linux

install: pip install tox

script: tox

notifications:
  email: false
