version: '{branch}-{build}'
build: off
configuration: Release
environment:
  #global:
  #  WITH_COMPILER: 'cmd /E:ON /V:ON /C .\ci\appveyor-with-compiler.cmd'
  matrix:
    - TESTENV: 'py27-64'
      INSTALL_LIBPYTHON: libpython
      PYTHON_VERSION: '2.7'
      MINICONDA_HOME: C:\Miniconda-x64

    - TESTENV: 'py27-32'
      INSTALL_LIBPYTHON: libpython
      PYTHON_VERSION: '2.7'
      MINICONDA_HOME: C:\Miniconda

    - TESTENV: 'py36-64'
      INSTALL_LIBPYTHON: libpython
      PYTHON_VERSION: '3.4'
      MINICONDA_HOME: C:\Miniconda36-x64

    - TESTENV: 'py36-32'
      INSTALL_LIBPYTHON: libpython
      PYTHON_VERSION: '3.4'
      MINICONDA_HOME: C:\Miniconda36

init:
  - ps: echo $env:TESTENV
install:
  - set PATH=%PATH%;C:\msys64\mingw64\bin
  - '%MINICONDA_HOME%\Scripts\conda config --set always_yes yes'
  - '%MINICONDA_HOME%\Scripts\conda update -q conda'
  - '%MINICONDA_HOME%\Scripts\conda create -q -p C:\pythontest python=%PYTHON_VERSION% %INSTALL_LIBPYTHON% pytest numpy'
  # remove file which conflicts with installation of package 'readme' on case-insensitive file systems
  - del C:\pythontest\Lib\site-packages\README
  # to stop the unnecessary "Only MS compiler supported with gfortran on win64" error on some configurations (numpy 1.9?)
  - '%MINICONDA_HOME%\Scripts\activate C:\pythontest'
  - '%INSTALL_EXTRA_DEPS%'
  - python setup.py
test_script:
  - 'py.test tests'


